spring.application.name=marketplace
spring.jackson.time-zone=Europe/Moscow

# ===============================
# SERVER
# ===============================
server.port=8080

# ===============================
# DATABASE (PostgreSQL)
# ===============================
spring.datasource.url=jdbc:postgresql://localhost:5432/marketplace_db
spring.datasource.username=postgres
spring.datasource.password=1111
spring.datasource.driver-class-name=org.postgresql.Driver

# ===============================
# JPA / HIBERNATE
# ===============================
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.open-in-view=false

# ===============================
# JWT
# ===============================
jwt.secret=CHANGE_ME_TO_LONG_RANDOM_SECRET_32_CHAR_MINIMUM
jwt.expiration-minutes=60

# ===============================
# BACKUP
# ===============================
#backup.dir=./backups
#backup.pg_dump_path=pg_dump


# ===== Backup/Restore settings =====
backup.pgDumpPath=C:/Program Files/PostgreSQL/13/bin/pg_dump.exe
backup.psqlPath=C:/Program Files/PostgreSQL/13/bin/psql.exe

backup.host=localhost
backup.port=5432
backup.dbName=marketplace_db
backup.user=postgres
backup.password=1111

backup.dir=C:/temp/marketplace_backups

backup.cron=0 0 2 * * *


