spring.application.name=marketplace
# ===============================
# SERVER
# ===============================
server.port=8080

# ===============================
# DATABASE (PostgreSQL)
# ===============================
spring.datasource.url=jdbc:postgresql://localhost:5432/marketplace_db
spring.datasource.username=postgres
spring.datasource.password=1111
spring.datasource.driver-class-name=org.postgresql.Driver

# ===============================
# JPA / HIBERNATE
# ===============================
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.open-in-view=false

# ===============================
# JWT
# ===============================
jwt.secret=CHANGE_ME_TO_LONG_RANDOM_SECRET_32_CHAR_MINIMUM
jwt.expiration-minutes=60

# ===============================
# BACKUP
# ===============================
backup.dir=./backups
backup.pg_dump_path=pg_dump